### ISSUE TITLE
Build error after download, install, and try to serve

### ISSUE THREAD

**Issue by Ridermansb** [auth0-community/auth0-emberjs2-sample#3]
After `ember s` .. in `localhost:4200` ...

**Same not occur if I clone the repo, just when I download from [website](https://manage.auth0.com/#/applications/XXXXXXX/quickstart)**

```
Build error

modules/ember-ajax/errors.js (in /Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/tmp/babel-input_base_path-BLgo1MZN.tmp/0)

The Broccoli Plugin: [Babel] failed with:
ReferenceError: [BABEL] modules/ember-ajax/errors.js: Unknown option: /Users/ridermansb/Downloads/.babelrc.presets
    at Logger.error (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/broccoli-babel-transpiler/index.js:105:21)
    at Babel.processString (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/broccoli-babel-transpiler/index.js:204:25)

The broccoli plugin was instantiated at: 
    at Babel.Plugin (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new Babel (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Object.registry.add.toTree (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/ember-cli-babel/index.js:23:52)
    at /Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at Class.Addon.preprocessJs (/Users/ridermansb/Downloads/auth0-emberjs2-sample-sample/node_modules/ember-cli/lib/models/addon.js:724:23)
```

**Comment by TylerJNewman** [comment]
I am getting something similar:
```
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: modules/ember-inflector/index.js
The Broccoli Plugin: [Babel] failed with:
ReferenceError: [BABEL] modules/ember-inflector/index.js: Unknown option: /Users/Tyler/working/.babelrc.presets
    at Logger.error (/Users/Tyler/working/webtask/01-login/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/Tyler/working/webtask/01-login/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/Tyler/working/webtask/01-login/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/Tyler/working/webtask/01-login/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/Tyler/working/webtask/01-login/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/Tyler/working/webtask/01-login/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/Tyler/working/webtask/01-login/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/Tyler/working/webtask/01-login/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/Tyler/working/webtask/01-login/node_modules/broccoli-babel-transpiler/index.js:105:21)
    at Babel.processString (/Users/Tyler/working/webtask/01-login/node_modules/broccoli-babel-transpiler/index.js:204:25)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/Tyler/working/webtask/01-login/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/Tyler/working/webtask/01-login/node_modules/broccoli-persistent-filter/index.js:60:10)
    at new Babel (/Users/Tyler/working/webtask/01-login/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/Users/Tyler/working/webtask/01-login/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Object.toTree (/Users/Tyler/working/webtask/01-login/node_modules/ember-cli-babel/index.js:23:52)
    at /Users/Tyler/working/webtask/01-login/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/Users/Tyler/working/webtask/01-login/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at Function.module.exports.preprocessJs (/Users/Tyler/working/webtask/01-login/node_modules/ember-cli-preprocess-registry/preprocessors.js:175:10)
    at CoreObject.preprocessJs (/Users/Tyler/working/webtask/01-login/node_modules/ember-cli/lib/models/addon.js:818:25)
```

**Comment by TylerJNewman** [comment]
deleting the .babelrc file in the parent directory works
in your case, delete 
```
/Users/ridermansb/Downloads/.babelrc
```

**Comment by beardaway** [comment]
Hey there folks!

I'm super thankful that you managed to share knowledge at that time and solve your issue. 

We're terribly sorry for such delay in response. We're working on providing you better developer experience in the future, step by step, and still are a little bit people resources constraint so thanks for understanding!

Glad you make it and sorry for delay on our end!
